### ISSUE TITLE
wishlist: hide the UI after data is sent

### ISSUE THREAD

**Issue by slippycheeze** [Intergalactic-Astronomical-Union/ATEL-EDMC#15]
I find myself, annoyingly, somewhat short on vertical space in the EDMC window.   (I know, I know.)

Anyway, the ATEL plugin keeps a constant bit of UI present telling me that it has successfully sent data; this is almost always going to be the case.  Importantly, too, there is **nothing** I should do in response to that fact.   Things worked, this is good.

I'd like it if the plugin showed nothing – hid its UI entirely – if that was all that was going on.  That way it stays completely silent when there is nothing for me to do.   

Displaying UI on failure is entirely reasonable, and appreciated: I have something to do then, figuring out why, and potentially fixing it.  So showing UI then, good. :)

Thank you.

**Comment by Elite-IGAU** [comment]
So instead of the one line of text:  ""Waiting for data..."" the ask is to have nothing in the UI? 

The UI is updated on events from the journal, so we can't clear after an event unless another event occurs in the journal. 
ATEL-EDMC keys off FSDJump event, and the CodexEntry events. 

Since FSDJump happens regularly, we can clear the UI each jump and update the status with one line of fairly unobtrusive text: ""Waiting for data...""
